FROM golang:1.25 AS build

WORKDIR /go/src/app
COPY . .

RUN
RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 go build -o /go/bin/app ./cmd/mock

FROM gcr.io/distroless/static-debian12

COPY --from=build --chown=nonroot:nonroot /go/bin/app /
USER nonroot

ENTRYPOINT ["/app"]
